name: Lint
on:
  pull_request:

jobs:
  test:
    name: Lint
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: shellcheck sver
      - uses: mfinelli/setup-shfmt@v3
      - run: shfmt -i 2 -ci -d sver
